### ISSUE TITLE
cssnano is throwing an error in the build

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#1363]
- Pull code
- Run `./run build`
- The following error appears in the console;

```
TypeError: error.setMessage is not a function
    at LazyResult.handleError (/Users/barrymcgee/projects/vanilla-framework/node_modules/postcss/lib/lazy-result.js:162:23)
    at /Users/barrymcgee/projects/vanilla-framework/node_modules/postcss/lib/lazy-result.js:196:27
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: error.showSourceCode is not a function
(node:17) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 9.56s.
```

**Comment by barrymcgee** [comment]
I've raised an issue on the `gulp-cassnano` repo relating to this: https://github.com/ben-eb/gulp-cssnano/issues/89

**Comment by Caleb-Ellis** [comment]
Issue resolved as of #1359

**Comment by barrymcgee** [comment]
@Caleb-Ellis This issue was not resolved as part of #1359, it was created as part of #1359?

**Comment by Caleb-Ellis** [comment]
@barrymcgee My mistake. I'm not getting the error and assumed it was fixed. Are you still getting the TypeError?

**Comment by kwm14** [comment]
Closing as we can't replicate issue. If errors are still happening in build please file a new bug 😄
